# Site settings
title: Watkin
email: jski.chen@gmail.com
header-img: img/top.jpg
description: 小小世界
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.wkchen.com/" # the base hostname & protocol for your site\

weibo_username:     1985790613
zhihu_username:     watkin
# github_username:    watkin
twitter_username:  jskiChen
#facebook_username:  jskiChen

# Build settings
markdown: kramdown
highlight: true
paginate: 5

source:      .
destination: ../watkin_web/_site

port:    4000
host:    127.0.0.1

comments :
  provider : duoshuo
  duoshuo :
    short_name : watkin
  disqus :
      short_name : watkin
  # ...