# Site settings
title: Watkin
email: jski.chen@gmail.com
description: 小小码农的世界
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.wkchen.com/" # the base hostname & protocol for your site
twitter_username: jskiChen
github_username:  watkin

# Build settings
markdown: kramdown
highlight: true


source:      .
destination: ../watkin_web/_site

port:    4000
host:    127.0.0.1

comments :
  provider : duoshuo
  duoshuo :
    short_name : watkin
  disqus :
      short_name : watkin
  # ...